app/blueprints/resources.py
from flask import Blueprint, render_template, abort, Markup, redirect, url_for

bp = Blueprint('resources', __name__)


@bp.route('/resources/<resc_name>')
def selection(resc_name=None):
    print(resc_name)
    return redirect(url_for("index"))

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
	<meta charset=utf-8 />
    <title>{% block title %}{% endblock %}</title>
    <meta name = "description" content = "Nigeria SE4ALL Webmap is an interactive display of geographic information on electrification planning for minigrid developers and will keep updated as new grid data is available.">
    <meta property="og:image" content="{{ url_for('static', filename='logos/logo-5-blitz.png') }}">
    <meta property="og:title" content="Interactive Webmap for electrification planning in Nigeria">
    <meta property="og:type" content="Website">
    <meta property="og:description" content="Nigeria SE4ALL Webmap is an interactive display of geographic information on electrification planning for minigrid developers and will keep updated as new grid data is available.">
    <meta property="og:url" content="https://nigeriase4all.gov.ng/map">

	<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no" />
        <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <script type=text/javascript>
           $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
        </script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha512-bnIvzh6FU75ZKxp0GXLH9bewza/OIw6dLVh9ICg0gogclmYGguQJWl8U30WpbsGTqbIiAwxTsbe76DErLq5EDQ==" crossorigin="anonymous"></script>

    {% block head %}{% endblock %}
</head>

<body>

    <div class="reveal level grid-x" id="video-popup" data-reveal>
      <div class="cell popup-title">Get a tour of the NIGERIA SE4ALL map</div>
      <div class="cell">
        <!-- the src of the iframe is defined in maps/index.html-->
        <iframe id="nigeria-se4all-video" class="nigeria-se4all-video" width="600" height="338" src="" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </div>
      <p class="cell">

          <button data-close aria-label="Close modal" type="button">
            <img src="{{ url_for('static', filename='img/icons/i_skip_g.svg') }}">
            Skip
          </button></p>
    </div>

  {% include 'popups.html' %}

  {% block content %}{% endblock %}


</body>

</html>

app/templates/popups.html
  <div class="reveal level" id="warning-browser-not-supported" data-reveal>
    <h2>Warning</h2>
    <p>This webmap is not optimized for browsers other than Chrome, Firefox and Opera.</p>
    <p>For the full functionality please visit from one of these browsers.</p>
    <div class="sidebar__btn">
      <button data-close aria-label="Close modal" type="button">
        Understood
      </button>
    </div>
  </div>

app/templates/sidebar_checkbox.html
 {% macro input(id, label, visible=['national', 'state', 'village'],filter_func=False,help_icon=False, help_link="", sub_panels=False) -%}
    <div class="grid-x">
      <div class="cell sidebar-panel {{ assign_visibility(visible) }}" id="{{ id }}TopLevelPanel">
        <div class="grid-x sidebar-panel-item is-active" id="{{ id }}Panel" data-accordion-item>
          <div class="cell small-8">
            <p href="#" class="sidebar-panel-item-title">
              {{ label }}
              {% if help_icon %}
                <a href="{{ url_for('resources.selection', resc_name=help_link) }}" target="_blank" rel="noreferrer">
                  <img src="{{ url_for('static', filename='img/icons/i_info.svg') }}">
                </a>
              {% endif %}
            </p>
          </div>
          {% if filter_func %}
          <div class="cell small-2 sidebar-panel-item-icon">
            <img
                    id="{{ id }}_filter"
                    class="filter_icon"
                    src="{{ url_for('static', filename='img/icons/i_funnel_dark_gray.svg') }}"
                    onclick="{{ id }}_filter_fun()"
                    title="Click on the funnel to expand filters"
            >
          </div>
          {% endif %}
          {% if sub_panels %}
          <div class="cell small-2 sidebar-panel-item-icon">
            <img
                    id="{{ id }}_expand"
                    class="expand_icon"
                    src="{{ url_for('static', filename='img/icons/i_arrow_up_g.svg') }}"
                    onclick="{{ id }}_toggle_fun()"
                    title="Click on the funnel to expand filters"
                    name="expanded"
            >
          </div>
          {% endif %}
          <div class="cell small-2">
            <div class="sidebar-panel-item-button">
              <input class="switch-input" id="{{ id }}Checkbox" type="checkbox" onclick="{{ id }}_cb_fun(trigger='user')" value="false">
              <label class="switch-paddle" for="{{ id }}Checkbox">
              </label>
            </div>
          </div>
        </div>
      </div>
    </div>
{%- endmacro %}

{% macro sub_panel(id, label, visible=['national', 'state', 'village'],filter_func=False,help_icon=False, help_link="") -%}
    <div class="grid-x">
      <div class="cell sidebar-panel sidebar-subpanel {{ assign_visibility(visible) }}" id="{{ id }}TopLevelPanel">
        <div class="grid-x sidebar-panel-item is-active" id="{{ id }}Panel" data-accordion-item>
          <div class="cell small-8">
            <p href="#" class="sidebar-panel-item-title sidebar-subpanel">
              {{ label }}
              {% if help_icon %}
                <a href="{{ url_for('resources.selection', resc_name=help_link) }}" target="_blank" rel="noreferrer">
                  <img src="{{ url_for('static', filename='img/icons/i_info.svg') }}">
                </a>
              {% endif %}
            </p>
          </div>
          {% if filter_func %}
          <div class="cell small-2 sidebar-panel-item-icon">
            <img
                    id="{{ id }}_filter"
                    class="filter_icon"
                    src="{{ url_for('static', filename='img/icons/i_funnel_dark_gray.svg') }}"
                    onclick="{{ id }}_filter_fun()"
                    title="Click on the funnel to expand filters"
            >
          </div>
          {% endif %}
          <div class="cell small-2">
            <div class="sidebar-panel-item-button">
              <input class="switch-input" id="{{ id }}Checkbox" type="checkbox" onclick="{{ id }}_cb_fun(trigger='user')" value="false">
              <label class="switch-paddle" for="{{ id }}Checkbox">
              </label>
            </div>
          </div>
        </div>
      </div>
    </div>
{%- endmacro %}



{% macro filter_title(id, label, name, spin_id, visible={'state': 'show', 'village': 'show'}, extra_class="") -%}
<div class="grid-x">
  <div class="cell {{ assign_visibility(visible) }}">
    <div class="sidebar-panel sidebar-panel-content content-filter hidden-filter sidebar-panel-filter-label {{ extra_class }}" name="{{ name }}">
      <div class="sidebar-panel-item sidebar-panel-item-filter grid-x">
        <div href="#" class="cell small-10 sidebar-panel-item-title sidebar-panel-item-title-filter">
          <p>{{ label }}<span id="{{ id }}"></span></p>
        </div>
        <div class="cell small-2">
          <div id="{{ spin_id }}" class="sp sp-circle is-hidden"></div>
        </div>
      </div>
    </div>
  </div>
</div>
{%- endmacro %}


{% macro filter_opt_toggle(id, label, name, visible={'state': 'show', 'village': 'show'}, help_icon=False, help_text="", extra_class="") -%}
 <div class="grid-x">
  <div class="cell sidebar-panel {{ assign_visibility(visible) }}">
    <div class="grid-x sidebar-panel sidebar-panel-content content-filter hidden-filter {{ extra_class }}" name="{{ name }}">

      <div class="cell small-8 sidebar-panel-item sidebar-panel-item-filter">
        <p class="sidebar-panel-item-title-filterlabel"> <img class="option_icon" src="{{ url_for('static', filename='img/icons/generation_icon_'+ id + '.svg') }}" > {{ label }}</p>
      </div>
      <div class="cell small-2">
        <div class="sidebar-panel-item-button">
          <input class="switch-input" id="{{ id }}Checkbox" type="checkbox" onclick="{{ id }}_cb_fun(trigger='user')" value="false">
          <label class="switch-paddle" for="{{ id }}Checkbox">
          </label>
        </div>
      </div>
    </div>
  </div>
</div>
{%- endmacro %}

{% macro filter_opt(id, label, name, visible={'state': 'show', 'village': 'show'}, help_icon=False, help_text="", extra_class="") -%}
<div class="grid-x">
  <div class="cell {{ assign_visibility(visible) }}">
    <div class="sidebar-panel sidebar-panel-content content-filter hidden-filter {{ extra_class }}" name="{{ name }}">
      <div class="sidebar-panel-item sidebar-panel-item-filter">
        <p href="#" class="sidebar-panel-item-title-filterlabel">
          {{ label }}
          {% if help_icon %}
          <button type="button" data-toggle="{{ id }}-filter-info">
            <img src="{{ url_for('static', filename='img/icons/i_info_w.svg') }}">
          </button>
          <div class="dropdown-pane filter-tooltip" id="{{ id }}-filter-info" data-dropdown data-hover="true" data-hover-pane="true" data-position="top" data-alignment="center" data-allow-overlap="true">
            {{ help_text|safe }}
          </div>
          {% endif %}
        </p>
        <div class="filter">
          <div class="filter__slider" id="{{ id }}"></div>
        </div>
      </div>
    </div>
  </div>
</div>
{%- endmacro %}

 {% macro filter_check_boxes(id, label, name, visible={'state': 'show', 'village': 'show'}, extra_class="") -%}
<div class="grid-x">
  <div class="cell {{ assign_visibility(visible) }}">
    <div class="sidebar-panel sidebar-panel-content content-filter hidden-filter {{ extra_class }}" name="{{ name }}">
      <div class="sidebar-panel-item sidebar-panel-item-filter grid-x">
        <div class="cell small-3 sidebar-panel-item-title-filterlabel">Minigrids</div>
        <div class="cell small-1"><input type="checkbox" class="custom_tickbox" id="minigridTickbox" onclick="minigrid_cb_fun(trigger='user')" value="false"><label class="custom_tickbox" for="minigridTickbox"></label></div>
        <div class="cell small-3 sidebar-panel-item-title-filterlabel">Power Plants</div>
        <div class="cell small-1"><input type="checkbox" class="custom_tickbox" id="powerplantTickbox" onclick="powerplant_cb_fun(trigger='user')" value="false"><label class="custom_tickbox" for="powerplantTickbox"></label></div>
      </div>
    </div>
  </div>
</div>
{%- endmacro %}


{% macro filter_download_btn(id, label, name, visible={'state': 'show', 'village': 'show'}) -%}
<div class="grid-x">
  <div class="cell {{ assign_visibility(visible) }}">
    <div class="sidebar-panel sidebar-panel-content content-filter hidden-filter" name="{{ name }}">
      <div class="sidebar-panel-item sidebar-panel-item--download">
        <div id="{{ id }}" class="download__btn">
          <button onclick="download_clusters_fun()">{{ label}}</button>
        </div>
      </div>
    </div>
  </div>
</div>
{%- endmacro %}